### ISSUE TITLE
[BUG]: No module named LinkedIn

### ISSUE THREAD

**Issue by muhammadhazrat** [surapuramakhil-org/Job_hunt_assistant#11]
### Describe the bug

2024-12-20 09:14:52.002 | DEBUG    | src.job_application_profile:__init__:120 - Processing work_preferences
2024-12-20 09:14:52.002 | DEBUG    | src.job_application_profile:__init__:122 - Work_preferences processed: WorkPreferences(remote_work='No', in_person_work='Yes', open_to_relocation='Yes', willing_to_complete_assessments='Yes', willing_to_undergo_drug_tests='Yes', willing_to_undergo_background_checks='Yes')
2024-12-20 09:14:52.002 | DEBUG    | src.job_application_profile:__init__:138 - Processing availability
2024-12-20 09:14:52.002 | DEBUG    | src.job_application_profile:__init__:140 - Availability processed: Availability(notice_period='04/01/2025')
2024-12-20 09:14:52.002 | DEBUG    | src.job_application_profile:__init__:156 - Processing salary_expectations
2024-12-20 09:14:52.002 | DEBUG    | src.job_application_profile:__init__:158 - salary_expectations processed: SalaryExpectations(salary_range_usd='40000 - 200000')
2024-12-20 09:14:52.002 | DEBUG    | src.job_application_profile:__init__:172 - JobApplicationProfile initialization completed successfully.
2024-12-20 09:14:57.746 | ERROR    | __main__:main:341 - Runtime error: Error running the bot: No module named 'src.job_portals.linkedIn' Traceback (most recent call last):
  File "C:\Users\muham\OneDrive - Higher Education Commission\MacBook_Air\Drexel\Drexel Uni\Job\Job_hunt_assistant\main.py", line 276, in create_and_run_bot
    job_portal = get_job_portal(
                 ^^^^^^^^^^^^^^^
  File "C:\Users\muham\OneDrive - Higher Education Commission\MacBook_Air\Drexel\Drexel Uni\Job\Job_hunt_assistant\src\job_portals\base_job_portal.py", line 208, in get_job_portal
    from src.job_portals.linkedIn.linkedin import LinkedIn
ModuleNotFoundError: No module named 'src.job_portals.linkedIn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\muham\OneDrive - Higher Education Commission\MacBook_Air\Drexel\Drexel Uni\Job\Job_hunt_assistant\main.py", line 330, in main
    create_and_run_bot(parameters, llm_api_key)
  File "C:\Users\muham\OneDrive - Higher Education Commission\MacBook_Air\Drexel\Drexel Uni\Job\Job_hunt_assistant\main.py", line 300, in create_and_run_bot
    raise RuntimeError(f"Error running the bot: {str(e)}")
RuntimeError: Error running the bot: No module named 'src.job_portals.linkedIn'

Exception ignored in: <function Chrome.__del__ at 0x000002B2216D27A0>
Traceback (most recent call last):
  File "C:\Users\muham\OneDrive\Desktop\Job\Auto_Jobs_Applier_AIHawk\virtual\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
    self.quit()
  File "C:\Users\muham\OneDrive\Desktop\Job\Auto_Jobs_Applier_AIHawk\virtual\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
    time.sleep(0.1)
OSError: [WinError 6] The handle is invalid

### Branch

None

**Comment by surapuramakhil** [comment]
@muhammadhazrat LinkedIn has been removed due to its User Agreement policy.

join the discord (link on ReadMe) for latest updates.

**Comment by surapuramakhil** [comment]
@muhammadhazrat some useful trackers

https://github.com/orgs/surapuramakhil-org/projects/1
